import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/login');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('testUser@gmail.com');
  await page.getByRole('textbox', { name: 'Email' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('testuser');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('testUser');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('textbox', { name: 'Password' }).dblclick();
  await page.getByRole('textbox', { name: 'Password' }).fill('testUser');
  await page.getByRole('textbox', { name: 'Password' }).press('Enter');
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('button', { name: 'Edit secret' }).nth(4).click();
  await page.getByRole('textbox', { name: 'Secret Value' }).click();
  await page.getByRole('textbox', { name: 'Secret Value' }).click();
  await page.getByRole('textbox', { name: 'Secret Value' }).click();
  await page.getByRole('textbox', { name: 'Secret Value' }).click();
  await page.getByRole('textbox', { name: 'Secret Value' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Secret Value' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Secret Value' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Secret Value' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Secret Value' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Secret Value' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Secret Value' }).press('ArrowRight');
  await page.getByRole('textbox', { name: 'Secret Value' }).fill('this is a something top secret updated!');
  await page.getByRole('button', { name: 'Update Secret' }).click();
  await page.getByRole('button', { name: 'Reveal secret' }).nth(2).click();
  await page.getByText('this is a something top').click();
  await page.getByRole('button', { name: 'Hide secret' }).click();
  await page.getByRole('button', { name: 'Delete secret' }).nth(2).click();
  await page.getByRole('button', { name: 'Delete' }).click();
});